# Generated by Django 6.0.3 on 2026-04-02 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='statuc',
            new_name='status',
        ),
    ]
